image: docker:20.10.6-dind

variables:
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:20.10.6-dind

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build -t gitlab-master.nvidia.com:5005/whicks/triton_fil_backend -f ops/Dockerfile .

build-tests:
  stage: build-tests
  script:
    - docker build -t triton_test -f qa/Dockerfile ./qa

run-tests:
  stage: test
  script:
    - docker run --gpus all --rm -it triton_test

deploy:
  stage: deploy
  script:
    - echo 'This is where we would push the container'
