build:
  stage: build
  script:
    - docker build -t gitlab-master.nvidia.com:5005/whicks/triton_fil_backend -f ops/Dockerfile .
    - docker build -t triton_test -f qa/Dockerfile ./qa

test:
  stage: test
  script:
    - mkdir /tmp/$CI_BUILD_REF
    - docker run -v /tmp/$CI_BUILD_REF:/logs --gpus all --rm triton_test
  artifacts:
    paths:
      - /tmp/$CI_BUILD_REF/server.log

deploy:
  stage: deploy
  script:
    - echo 'This is where we would push the container'
