build:
  stage: build
  script:
    - >
      docker pull
      gitlab-master.nvidia.com:5005/dl/dgx/tritonserver:master-py3-base
    - >
      docker build
      -t gitlab-master.nvidia.com:5005/whicks/triton_fil_backend
      --build-arg
      BASE_IMAGE=gitlab-master.nvidia.com:5005/dl/dgx/tritonserver:master-py3-base
      -f ops/Dockerfile .
    - docker build -t triton_test -f qa/Dockerfile ./qa

test:
  stage: test
  script:
    - mkdir $PWD/$CI_BUILD_REF
    - docker run -v $PWD/$CI_BUILD_REF:/logs --gpus all --rm triton_test
  artifacts:
    paths:
      - $PWD/$CI_BUILD_REF/server.log

deploy:
  stage: deploy
  script:
    - docker push gitlab-master.nvidia.com:5005/whicks/triton_fil_backend:latest
  only:
    - main

deploy-tag:
  stage: deploy
  script:
    - docker push gitlab-master.nvidia.com:5005/whicks/triton_fil_backend:$CI_COMMIT_TAG
  only:
    - tags
