name: triton_scripts
channels:
  - conda-forge
  - nvidia
  - rapidsai
dependencies:
  - cudatoolkit=11.4
  - cuml=22.10
  - libcusolver<=11.4.1.48
  - libcusparse<=12.0
  - python=3.8
  - scikit-learn
  - treelite=2.4.0
